workspace/music_app/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'music_app'

urlpatterns = [
    # /music
    url(r'^$', views.ViewIndex.as_view(), name="index"),
    
    # /music/album/id_number
     url(r'album/(?P<pk>[0-9]+)/$', views.DetailView.as_view() , name="detail"),
    
    # add new album from a form 
    # music/album/add
    url(r'album/add/$', views.AlbumCreate.as_view(), name="album-add"),
    
    # edit album
    url(r'(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name="album-update"),
    
     # delete album
     url(r'album/(?P<pk>\d+)/delete/$', views.AlbumDelete.as_view(), name="album-delete"),
    
    
    ]

workspace/music_website_django/urls.py
from django.conf import settings 
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('music_app.urls')),
    url(r'^music/', include('music_app.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    
    

workspace/.c9/metadata/workspace/music_app/models.py
{"filter":false,"title":"models.py","tooltip":"/music_app/models.py","undoManager":{"mark":-1,"position":-1,"stack":[]},"ace":{"folds":[],"scrolltop":67.00004196166992,"scrollleft":0,"selection":{"start":{"row":32,"column":1},"end":{"row":32,"column":1},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":{"row":0,"state":"start","mode":"ace/mode/python"}},"timestamp":1469462601769,"hash":"a5cbdbc4a621f3670cf6e69c30f161d64455274f"}

workspace/music_app/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse 

# Create your models here..

# Albums
class Album(models.Model):
    
    album_title =  models.CharField(max_length=500)
    artist = models.CharField(max_length=500)
    genre  = models.CharField(max_length=1000)
    album_logo= models.FileField() # upload a file
    
    
    def get_absolute_url(self):
        return reverse('music_app:detail', kwargs={'pk':self.pk})
    
    def __str__(self):
        return self.album_title + "-" + self.artist


# # Songs
class Song(models.Model):
    album= models.ForeignKey(Album, on_delete= models.CASCADE)
    song_title= models.CharField(max_length=500)
    file_type=models.CharField(max_length=100)
    is_favorite= models.BooleanField(default=False)
    
    def __str__(self):
        
        return self.song_title 
 

workspace/music_app/forms.py
from django.contrib.auth.models import User
from django import forms



class UserForm(forms.ModelForm):
    
    password = forms.CharField(widget=forms.PasswordInput) # to add the asterisk feature for hiding passwords
    
    # inforamtion about the class you are using
    class Meta:
        model = User
        fields = ['username','email','password']

workspace/music_app/views.py
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, get_object_or_404 , redirect
from django.http import HttpResponse
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from . models import Album, Song
from .forms import UserForm


# Generic views
class ViewIndex(generic.ListView):
    
    template_name = "music_app/index.html"
    context_object_name = 'all_album'
    
    def get_queryset(self):
        
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music_app/details.html'

# view album page
class AlbumCreate(CreateView):
    model = Album
    fields = ['album_title', 'artist', 'genre', 'album_logo']
    

# for editing the page
class AlbumUpdate (generic.UpdateView):
    model = Album
    fields = ['album_title', 'artist', 'genre', 'album_logo']
    success_url  = reverse_lazy('music_app:index')
    
# delete page
class AlbumDelete(DeleteView):
    model= Album
    success_url  =  reverse_lazy('music_app:index')

    
    

workspace/music_app/templates/music_app/album_form.html
{%extends "music_app/base.html"%}

{% block title %} Add Album  {% endblock %}
<!--FORM-->
{%block body%}
<div class="container-fluid">
    <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Album</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music_app/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
</div>
{%endblock%}    
  
    

workspace/music_app/templates/music_app/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title%}{% endblock %}</title>
        <meta  charset="UTF-8">
        <link rel="stylesheet" href="{% static 'music_app/style.css'%}" type="text/css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" type="text/css" />
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <link rel="shortcut icon" type="image/png" href="{%  static 'music_app/images/drum.ico' %}"/> <!--ICON -->
        <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js'></script>
    </head>
    
<body>
    <nav class="navbar navbar-default">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music_app:index' %}">Muzzika</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'music_app:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a></li>
                <li>
                    <a href="{% url 'music_app:index' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                </a></li>
            </ul>
            <!--END-->
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <!--END-->
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'music_app:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                
                 <li>
                    <a href="{% url 'music_app:index' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Signup
                    </a>
                </li>
                
                <li>
                    <a href="{% url 'music_app:index' %}">
                        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Login
                    </a>
                </li>
            </ul>
            <!--END-->
        </div>

    </div>
</nav>
<!--END of NAV-->

<!--Body Block-->
{% block body %}
{%  endblock %}
</body>
</html>

workspace/music_app/templates/music_app/details.html
{% extends "music_app/base.html" %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} {{album.album_title }} {%endblock%} </title>
    </head>
<body>
    
    {% block body %}
        <h1>Albums</h1>
        <img src="{{album.album_logo.url}}"></img>
        
        <h2> Album Title: {{ album.album_title}}</h2>
        <h3> Artist: {{album.artist}}</h3>
        
         <!--Error Alert-->
         {% if error_message%}
             <p><strong>{{ error_message }}</strong></p>
         {% endif %}
     
     <!---->
        
        {% for song in album.song_set.all  %}

                {{song.song_title}}
                    {%if song.is_favorite%} 
                        <img src="https://s32.postimg.org/u235vnmo5/rsz_1rsz_1rsz_star.png"></img>
                    {%endif%}<br>
        {% endfor%}
        
 {%endblock%}     
</body>
</html>

workspace/music_app/templates/music_app/form_template.html
<!--short cut to loop through all field and display them as inputs-->
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-12">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

workspace/music_app/templates/music_app/index.html
<!--load static files-->
{% extends "music_app/base.html" %}
<!DOCTYPE html>
<html>
    <head>
        <title>{%block title %} Muzzika {% endblock %}</title>
    </head>
    
<body>
{% block body %}
    <!--Album style-->
    <div class="container-fluid">
    {%if all_album %}  
      {%for album in all_album%}<!--loop through all albums-->
        <div class="col-sm-4 col-lg-2">
            <div class="thumbnail">
                <a href="{% url 'music_app:detail' album.id%}">
                    <img id="img-logo" src="{{album.album_logo.url}}" class="img-responsive">
                </a>
                <div class="caption">
                    <h2>{{ album.album_title }}</h2>
                    <h4>{{album.artist}}</h4>
                    <!--VIEW DETAILS-->
                    <a href="{% url 'music_app:detail' album.id %}" class="btn btn-primary btn-sm"> View Details</a>
                    
                    <!--DELETE BUTTON-->
                  <!-- Delete Album -->
                            <form action="{% url 'music_app:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                  
                  <!--FAVORTIE BUTTON-->
                  <a href="{% url 'music_app:detail' album.id %}" class="btn btn-default btn-sm glyphicon glyphicon-star"></a>
                </div>
                
            </div> 
            <!--END thumbnail-->
        </div>
        <!--END col-->
       {%endfor%}
       
<!--if there are no albums to show-->
        {%else%}
            <h1 id="no-album">There is no albums</h1>
        {%endif%}
</div>
<!--END container-->
{% endblock %}        
</body>
</html>